import { Link } from "react-router-dom";
import { ArrowIcon, PageMeta, ProjectsSection, ReviewsRail, TrustBar } from "../components";
import { services } from "../content";

export function HomePage() {
  return <main><PageMeta title="Elektriker i Växjö" description="Växjö Eltjänst hjälper privatpersoner, företag och fastigheter med kompletta elinstallationer i Växjö." />
    <section className="hero"><video className="hero-video" autoPlay muted loop playsInline preload="auto" poster="/images/project-23695.jpg"><source src="/media/hero-electrician-demo.mp4" type="video/mp4" /></video><div className="hero-overlay" /><div className="hero-content"><h1 className="sr-only">Växjö Eltjänst – din kompletta elpartner i Växjö</h1><span className="brand-mark brand-mark--hero"><span className="brand-mark__frame"><span className="brand-mark__name">ELTJÄNST</span></span><span className="brand-mark__city">VÄXJÖ</span></span><p className="hero-tagline">DIN KOMPLETTA ELPARTNER</p><Link className="hero-ghost-button" to="/kontakt#offert">Begär kostnadsfri offert</Link></div><span className="demo-badge">Tillfällig demovideo</span></section>
    <TrustBar />
    <section className="section services"><div className="container"><header className="section-heading"><span className="eyebrow">Vad vi gör</span><h2>Våra tjänster</h2></header><div className="services-grid">{services.map((service, index) => <article className="service-card" key={service.slug}><Link to={`/tjanster/${service.slug}`} className="service-card__image"><img src={service.image} alt="" loading="lazy" /><span className="service-card__number">0{index + 1}</span></Link><div className="service-card__body"><h3>{service.title}</h3><p>{service.description}</p><Link to={`/tjanster/${service.slug}`}>Läs mer <ArrowIcon /></Link></div></article>)}</div></div></section>
    <section className="section showreel"><div className="container showreel-grid"><div className="showreel-media"><video muted loop playsInline autoPlay preload="metadata" poster="/images/project-23491.jpg"><source src="/media/showreel-solar-demo.mp4" type="video/mp4" /></video><span className="video-label">Demomaterial · byt mot eget projekt</span></div><div className="showreel-copy"><span className="eyebrow eyebrow--light">Se skillnaden</span><h2>Precision i varje anslutning.</h2><p>Växjö Eltjänst levererar kompletta elinstallationer med hög teknisk kompetens, tydligt kvalitetsfokus och långsiktiga kundrelationer.</p><p>Från mindre servicearbeten till större entreprenader får du en lokal partner som tar ansvar för helheten.</p><Link className="button button--light" to="/om-oss">Lär känna oss <ArrowIcon /></Link></div></div></section>
    <section className="section why-section"><div className="container why-grid"><div className="why-intro"><span className="eyebrow eyebrow--light">Varför Växjö Eltjänst</span><h2>Lokalt ansvar. Starkare möjligheter.</h2><p>Väletablerad kompetens i Växjö, förstärkt av nätverket och resurserna i SELATEK.</p><div className="selatek-card"><img src="/images/selatek-partnership.jpeg" alt="SELATEK och Växjö Eltjänst" loading="lazy" /><span>En del av SELATEK sedan 2026</span></div></div><div className="reason-list">{[["01", "Hög teknisk kompetens", "Erfarna medarbetare och lösningar planerade för säkerhet, funktion och lång livslängd."], ["02", "Komplett leverans", "En partner för privatkunder, företag och fastigheter — från service till projekt."], ["03", "Stark lokal förankring", "Växjöbaserat team med fokus på långsiktiga relationer."]].map(([n, t, x]) => <article className="reason-card" key={n}><span>{n}</span><div><h3>{t}</h3><p>{x}</p></div></article>)}</div></div></section>
    <ProjectsSection compact /><ReviewsRail />
    <section className="section contact-band"><div className="container contact-band__inner"><div><span className="eyebrow eyebrow--light">Kom igång</span><h2>Redo att starta ditt projekt?</h2><p>Berätta vad du behöver hjälp med så återkommer vi med nästa steg.</p></div><Link className="button button--light" to="/kontakt#offert">Begär offert <ArrowIcon /></Link></div></section>
  </main>;
}
