export * from "./AboutPage";
export * from "./ContactPage";
export * from "./HomePage";
export * from "./IntegrityPage";
export * from "./NotFoundPage";
export * from "./ProjectsPage";
export * from "./ReviewsPage";
export * from "./ServicePage";
export * from "./ServicesPage";
